blank_issues_enabled: false
contact_links:
  - name: Dapr Community Support (Discord Invitation, Community meetings, etc.)
    url: https://github.com/dapr/community
    about: More information about the Dapr community and how to get involved.
  - name: Reporting security issues
    url: https://docs.dapr.io/operations/support/support-security-issues/
    about: Please report security vulnerabilities here.